=== perthi/logmaster/logging.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.1" vc:minVersion="1.1"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning">
    <xs:simpleType name="IPv4Address">
        <xs:annotation>
            <xs:documentation>IPv4 address in dot-decimal notation. Equivalent to
                [0-255].[0-255].[0-255].[0-255]</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="((1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])"/>
        </xs:restriction>
    </xs:simpleType>
     <xs:simpleType name="LogLevel">
          <xs:restriction base="xs:string"></xs:restriction>
     </xs:simpleType>
    <xs:simpleType name="DeviceID">
      <xs:restriction base="xs:string">
          <xs:minLength value="1"/>
          <!--  <xs:pattern value="[L][0-9]?[0-9]?[0-9]-[A-Z]?[A-Z]?[A-Z]?[A-Z][0-9]?[0-9]?[0-9]"/> -->
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="DeviceType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="SEM"/>
            <xs:enumeration value="MotorStepper"/>
            <xs:enumeration value="MotorVirtualXY"/>
            <xs:enumeration value="Solenoid"/>
            <xs:enumeration value="PWMSignal"/>
            <xs:enumeration value="PWMPower"/>
            <xs:enumeration value="SensorAnalogDirect"/>
            <xs:enumeration value="SensorLocal"/>
            <xs:enumeration value="SensorBoolDirect"/>
            <xs:minLength value="2"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="InputType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PNP"/>
            <xs:enumeration value="0-20mA"/>
            <xs:enumeration value="4-20mA"/>
            <xs:enumeration value="0-10V"/>
            <xs:enumeration value="PWM-RC"/>
            <xs:enumeration value="PWM-duty_cycle"/>
            <xs:enumeration value="SPI"/>
            <xs:enumeration value="I2C"/>
            <xs:enumeration value="Local"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="IntOrNothing">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base='xs:string'>
                    <xs:length value="0"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
     <xs:simpleType name="FloatOrNothing">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base='xs:string'>
                    <xs:length value="0"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:float">
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>

    <xs:simpleType name="DirectionRotational">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CW"/>
            <xs:enumeration value="CCW"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Direction">
        <xs:restriction base="xs:string">
            <xs:enumeration value=""/>
            <xs:enumeration value="POSITIVE"/>
            <xs:enumeration value="NEGATIVE"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="SensorLinearInputUnitConversion">
        <xs:sequence>
            <xs:element name="INPUT_TYPE" type="InputType"> </xs:element>
            <xs:element name="MIN_INPUT" type="FloatOrNothing"> </xs:element>
            <xs:element name="MAX_INPUT" type="FloatOrNothing"> </xs:element>
            <xs:element name="MIN_OUTPUT" type="FloatOrNothing"> </xs:element>
            <xs:element name="MAX_OUTPUT" type="FloatOrNothing"> </xs:element>
            <xs:sequence> </xs:sequence>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Thresholds">
        <xs:sequence>
            <xs:element name="ALARM_LOW" type="FloatOrNothing"> </xs:element>
            <xs:element name="WARNING_LOW" type="FloatOrNothing"> </xs:element>
            <xs:element name="WARNING_HIGH" type="FloatOrNothing"> </xs:element>
            <xs:element name="ALARM_HIGH" type="FloatOrNothing"> </xs:element>
            <xs:sequence> </xs:sequence>
        </xs:sequence>
      <!-- not supported by libxml2 <xs:assert test="ALARM_HIGH > WARNING_HIGH"/>
        <xs:assert test="WARNING_HIGH > WARNING_LOW"/>
        <xs:assert test="WARNING_LOW > ALARM_LOW"/> -->
    </xs:complexType>
    <xs:complexType name="Addressing">
        <xs:sequence>
            <xs:element name="DEVICE_ID" type="DeviceID"> </xs:element>
            <xs:element name="DEVICE_NAME" type="xs:string"/>
            <xs:element name="IP_ADDRESS" type="IPv4Address"/>
            <xs:sequence>
                <xs:element name="CARD" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MANUFACTURER_ID" type="xs:string"/>
                            <xs:element name="CARD_NAME" type="xs:string"/>
                            <xs:element name="CARD_ID" type="xs:int"/>
                            <xs:element name="DEVICE_PORT_NO" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="LOGGING" >
       <xs:complexType>
           <xs:sequence>
                <xs:element name="MOTOR_STEPPER"   maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="DEVICE_ADDRESS" type="Addressing"> </xs:element>
                            <xs:element name="DEVICE_TYPE" type="DeviceType" fixed="MotorStepper"/>
                            <xs:element name="STEP_UNIT_CONVERSION" maxOccurs="1" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="UNIT" type="xs:string"/>
                                        <xs:element name="UNIT_PER_STEP" type="xs:float"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="MOTOR_CONFIG" maxOccurs="1" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="DIRECTION_POSITIVE" type="DirectionRotational"/>
                                        <xs:element name="ENDSTOP_SOFT_POSITIVE"  type = "FloatOrNothing"/>
                                        <xs:element name="ENDSTOP_SOFT_NEGATIVE" type = "FloatOrNothing"/>
                                        <xs:element name="MAX_SPEED" type="xs:float"/>
                                        <xs:element name="SPEED" type="xs:float"/>
                                        <xs:element name="MAX_ACCELERATION" type="xs:float"/>
                                        <xs:element name="ACCELERATION" type="xs:float"/>
                                        <xs:element name="MAX_CURRENT" type = "xs:float"/>
                                        <xs:element name="CURRENT" type = "xs:float"/>
                                        <xs:element name="INACTIVE_TIMEOUT" type="xs:float"/>
                                        <xs:element name="INACTIVE_CURRENT" type="xs:float"/>
                                        <xs:element name="HOME_DEVICE_ID" type="xs:string"/>
                                        <xs:element name="HOME_VALUE" type="xs:float"/>
                                        <xs:element name="HOME_DIRECTION" type="Direction"/>
                                        <xs:element name="ENDSTOP_DEVICE_ID_POSITIVE" type="xs:string"/>
                                        <xs:element name="ENDSTOP_DEVICE_ID_NEGATIVE" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
               <xs:element name="MOTOR_VIRTUAL_XY"  maxOccurs="unbounded" minOccurs="0">
                   <xs:complexType>
                       <xs:sequence>
                           <xs:element name="IP_ADDRESS" type="IPv4Address" maxOccurs="1" minOccurs="1"/>
                           <xs:element name="DEVICE_ID" type="DeviceID" maxOccurs="1" minOccurs="1"/>
                           <xs:element name="DEVICE_TYPE" type="DeviceType" fixed="MotorVirtualXY"/>
                           <xs:element name="DEVICE_NAME"/>
                           <xs:element name="MOTOR_TRANSLATION" type = "DeviceID"/>
                           <xs:element name="MOTOR_ROTATION" type = "DeviceID"/>
                       </xs:sequence>
                   </xs:complexType>
               </xs:element>
               <xs:element name="SENSOR_ANALOG_DIRECT"  maxOccurs="unbounded" minOccurs="0">
                   <xs:complexType>
                       <xs:sequence>
                           <xs:element name="DEVICE_ADDRESS" type="Addressing" maxOccurs="1" minOccurs="1"/>
                           <xs:element name="DEVICE_TYPE" type="DeviceType" fixed="SensorAnalogDirect"/>
                           <xs:element name="UNIT_CONVERSION" type="SensorLinearInputUnitConversion" maxOccurs="1" minOccurs="1"/>
                           <xs:element name="THRESHOLDS" type="Thresholds" maxOccurs="1" minOccurs="1"/>
                           <xs:element name="DEVICE_ID_AUX" type="DeviceID" maxOccurs="1" minOccurs="1"/>
                       </xs:sequence>
                   </xs:complexType>
               </xs:element>
               <xs:element name="SENSOR_BOOL_DIRECT"  maxOccurs="unbounded" minOccurs="0">
                   <xs:complexType>
                       <xs:sequence>
                           <xs:element name="DEVICE_ADDRESS" type="Addressing" maxOccurs="1" minOccurs="1"/>
                           <xs:element name="DEVICE_TYPE" type="DeviceType" fixed="SensorBoolDirect"/>
                           <xs:element name="INPUT_TYPE" type="InputType"> </xs:element>
                           <xs:element name="ACTIVE_HIGH" type="xs:boolean"> </xs:element>
                           <xs:element name="ALARM" type="xs:boolean"> </xs:element>
                           <xs:element name="DEVICE_ID_AUX" type="DeviceID" maxOccurs="1" minOccurs="1"/>
                       </xs:sequence>
                   </xs:complexType>
               </xs:element>
               <xs:element name="SENSOR_LOCAL" maxOccurs="unbounded" minOccurs="0">
                   <xs:complexType>
                       <xs:sequence>
                           <xs:element name="DEVICE_ADDRESS" type="Addressing" maxOccurs="1" minOccurs="1"/>
                           <xs:element name="DEVICE_TYPE" type="DeviceType" fixed="SensorLocal"/>
                           <xs:element name="UNIT_CONVERSION" type="SensorLinearInputUnitConversion" maxOccurs="1" minOccurs="1"/>
                           <xs:element name="THRESHOLDS" type="Thresholds" maxOccurs="1" minOccurs="1"/>
                           <xs:element name="DEVICE_ID_AUX" type="DeviceID" maxOccurs="1" minOccurs="1"/>
                       </xs:sequence>
                   </xs:complexType>
               </xs:element>
  
               <xs:element name="SOLENOID"  maxOccurs="unbounded" minOccurs="0">
                   <xs:complexType>
                       <xs:sequence>
                           <xs:element name="DEVICE_ADDRESS" type="Addressing" maxOccurs="1" minOccurs="1"/>
                           <xs:element name="DEVICE_TYPE" type="DeviceType" fixed="Solenoid"/>
                           <xs:element name="MAX_CURRENT" type="xs:float"> </xs:element>
                           <xs:element name="ACTIVATE_CURRENT" type="xs:float"> </xs:element>
                           <xs:element name="HOLD_CURRENT" type="xs:float"> </xs:element>
                       </xs:sequence>
                   </xs:complexType>
               </xs:element>
               <xs:element name="PWM_SIGNAL" maxOccurs="unbounded" minOccurs="0">
                   <xs:complexType>
                       <xs:sequence>
                           <xs:element name="DEVICE_ADDRESS" type="Addressing" maxOccurs="1" minOccurs="1"/>
                           <xs:element name="DEVICE_TYPE" type="DeviceType" fixed="PWMSignal"/>
                           <xs:element name="UNIT_CONVERSION" type="SensorLinearInputUnitConversion" maxOccurs="1" minOccurs="1"/>
                           <xs:element name="MIN_LEVEL" type = "xs:float"/>
                           <xs:element name="MAX_LEVEL" type = "xs:float"/>
                       </xs:sequence>
                   </xs:complexType>
               </xs:element>
               <xs:element name="PWM_POWER" maxOccurs="unbounded" minOccurs="0">
                   <xs:complexType>
                       <xs:sequence>
                           <xs:element name="DEVICE_ADDRESS" type="Addressing" maxOccurs="1" minOccurs="1"/>
                           <xs:element name="DEVICE_TYPE" type="DeviceType" fixed="PWMPower"/>
                           <xs:element name="UNIT_CONVERSION" type="SensorLinearInputUnitConversion" maxOccurs="1" minOccurs="1"/>
                           <xs:element name="MIN_LEVEL" type = "xs:float"/>
                           <xs:element name="MAX_LEVEL" type = "xs:float"/>
                       </xs:sequence>
                   </xs:complexType>
               </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="unique_device_id">
<!--            <xs:selector xpath="*/DEVICE_ADDRESS/DEVICE_ID"/>-->
            <xs:selector xpath="*/DEVICE_ID"/>
            <xs:field xpath="."/>
        </xs:unique>
    </xs:element>
</xs:schema>

=== perthi/logmaster/logging.xml
<?xml version="1.0" encoding="UTF-8"?>




<!--<LOGGING xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="logging.xsd">
</LOGGING>-->



<LOGGING xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="logging.xsd">


<!-- Stepper motors -->
    <MOTOR_STEPPER>
        <DEVICE_ADDRESS>
            <DEVICE_ID>M2</DEVICE_ID>
            <DEVICE_NAME>Open/close motor starboard</DEVICE_NAME>
            <IP_ADDRESS>192.168.1.12</IP_ADDRESS>
            <CARD>
                <MANUFACTURER_ID>X-NUCLEO-IHM03A1</MANUFACTURER_ID>
                <CARD_NAME>Stepper motor driver 10 A</CARD_NAME>
                <CARD_ID>2</CARD_ID>
                <DEVICE_PORT_NO>1</DEVICE_PORT_NO>
            </CARD>
        </DEVICE_ADDRESS>
        <DEVICE_TYPE>MotorStepper</DEVICE_TYPE>
        <STEP_UNIT_CONVERSION>
            <UNIT>angle_deg</UNIT>
            <UNIT_PER_STEP>0.000078</UNIT_PER_STEP>
        </STEP_UNIT_CONVERSION>
        <MOTOR_CONFIG>
            <DIRECTION_POSITIVE>CW</DIRECTION_POSITIVE>
            <ENDSTOP_SOFT_POSITIVE></ENDSTOP_SOFT_POSITIVE>
            <ENDSTOP_SOFT_NEGATIVE></ENDSTOP_SOFT_NEGATIVE>
            <MAX_SPEED>1</MAX_SPEED>
            <SPEED>0.06</SPEED>
            <MAX_ACCELERATION>0.01</MAX_ACCELERATION>
            <ACCELERATION>0.01</ACCELERATION>
            <MAX_CURRENT>10</MAX_CURRENT>
            <CURRENT>9</CURRENT>
            <INACTIVE_TIMEOUT>100</INACTIVE_TIMEOUT>
            <INACTIVE_CURRENT>0.1</INACTIVE_CURRENT>
            <HOME_DEVICE_ID></HOME_DEVICE_ID>
            <HOME_VALUE>0</HOME_VALUE>
            <HOME_DIRECTION></HOME_DIRECTION>
            <ENDSTOP_DEVICE_ID_POSITIVE></ENDSTOP_DEVICE_ID_POSITIVE>
            <ENDSTOP_DEVICE_ID_NEGATIVE></ENDSTOP_DEVICE_ID_NEGATIVE>
        </MOTOR_CONFIG>
    </MOTOR_STEPPER>



<!-- Virtual motors -->


    <MOTOR_VIRTUAL_XY>
        <IP_ADDRESS>192.168.1.16</IP_ADDRESS>
        <DEVICE_ID>XY2</DEVICE_ID>
        <DEVICE_TYPE>MotorVirtualXY</DEVICE_TYPE>
        <DEVICE_NAME>C360 c-ring control</DEVICE_NAME>
        <MOTOR_TRANSLATION>M7</MOTOR_TRANSLATION>
        <MOTOR_ROTATION>M8</MOTOR_ROTATION>
    </MOTOR_VIRTUAL_XY>

    <MOTOR_VIRTUAL_XY>
        <IP_ADDRESS>192.168.1.15</IP_ADDRESS>
        <DEVICE_ID>XY1</DEVICE_ID>
        <DEVICE_TYPE>MotorVirtualXY</DEVICE_TYPE>
        <DEVICE_NAME>C180 c-ring control</DEVICE_NAME>
        <MOTOR_TRANSLATION>M5</MOTOR_TRANSLATION>
        <MOTOR_ROTATION>M6</MOTOR_ROTATION>
    </MOTOR_VIRTUAL_XY> 

<!-- Analog external sensors -->


    <SENSOR_ANALOG_DIRECT>
        <DEVICE_ADDRESS>
            <DEVICE_ID>S1</DEVICE_ID>
            <DEVICE_NAME>Flow line temperature</DEVICE_NAME>
            <IP_ADDRESS>192.168.1.12</IP_ADDRESS>
            <CARD>
                <MANUFACTURER_ID>POWER-IO-01</MANUFACTURER_ID>
                <CARD_NAME>PowerIO</CARD_NAME>
                <CARD_ID>4</CARD_ID>
                <DEVICE_PORT_NO>20</DEVICE_PORT_NO>
            </CARD>
        </DEVICE_ADDRESS>
        <DEVICE_TYPE>SensorAnalogDirect</DEVICE_TYPE>
        <UNIT_CONVERSION>
            <INPUT_TYPE>0-10V</INPUT_TYPE>
            <!-- <OUTPUT_UNIT>V</OUTPUT_UNIT> -->
            <MIN_INPUT>0</MIN_INPUT>
            <MAX_INPUT>10</MAX_INPUT>
            <MIN_OUTPUT>-40</MIN_OUTPUT>
            <MAX_OUTPUT>85</MAX_OUTPUT>
        </UNIT_CONVERSION>
        <THRESHOLDS>
            <ALARM_LOW></ALARM_LOW>
            <WARNING_LOW></WARNING_LOW>
            <WARNING_HIGH></WARNING_HIGH>
            <ALARM_HIGH></ALARM_HIGH>
        </THRESHOLDS>
        <DEVICE_ID_AUX>???</DEVICE_ID_AUX>
    </SENSOR_ANALOG_DIRECT>

    <SENSOR_ANALOG_DIRECT>
        <DEVICE_ADDRESS>
            <DEVICE_ID>S2</DEVICE_ID>
            <DEVICE_NAME>Habitat external temperature</DEVICE_NAME>
            <IP_ADDRESS>192.168.1.13</IP_ADDRESS>
            <CARD>
                <MANUFACTURER_ID>POWER-IO-01</MANUFACTURER_ID>
                <CARD_NAME>PowerIO</CARD_NAME>
                <CARD_ID>4</CARD_ID>
                <DEVICE_PORT_NO>20</DEVICE_PORT_NO>
            </CARD>
        </DEVICE_ADDRESS>
        <DEVICE_TYPE>SensorAnalogDirect</DEVICE_TYPE>
        <UNIT_CONVERSION>
            <INPUT_TYPE>4-20mA</INPUT_TYPE>
            <!-- <OUTPUT_UNIT>Â°C</OUTPUT_UNIT> -->
            <MIN_INPUT>4</MIN_INPUT>
            <MAX_INPUT>20</MAX_INPUT>
            <MIN_OUTPUT>-3.9</MIN_OUTPUT>
            <MAX_OUTPUT>79.4</MAX_OUTPUT>
        </UNIT_CONVERSION>
        <THRESHOLDS>
            <ALARM_LOW></ALARM_LOW>
            <WARNING_LOW></WARNING_LOW>
            <WARNING_HIGH></WARNING_HIGH>
            <ALARM_HIGH></ALARM_HIGH>
        </THRESHOLDS>
        <DEVICE_ID_AUX>???</DEVICE_ID_AUX>
    </SENSOR_ANALOG_DIRECT>

  

    <SENSOR_BOOL_DIRECT>
        <DEVICE_ADDRESS>
            <DEVICE_ID>S6</DEVICE_ID>
            <DEVICE_NAME>C180 translational end stop</DEVICE_NAME>
            <IP_ADDRESS>192.168.1.15</IP_ADDRESS>
            <CARD>
                <MANUFACTURER_ID>POWER-IO-01</MANUFACTURER_ID>
                <CARD_NAME>PowerIO</CARD_NAME>
                <CARD_ID>4</CARD_ID>
                <DEVICE_PORT_NO>20</DEVICE_PORT_NO>
            </CARD>
        </DEVICE_ADDRESS>
        <DEVICE_TYPE>SensorBoolDirect</DEVICE_TYPE>
        <INPUT_TYPE>PNP</INPUT_TYPE>
        <ACTIVE_HIGH>true</ACTIVE_HIGH>
        <ALARM>false</ALARM>
        <DEVICE_ID_AUX>???</DEVICE_ID_AUX>
    </SENSOR_BOOL_DIRECT>

    <SENSOR_BOOL_DIRECT>
        <DEVICE_ADDRESS>
            <DEVICE_ID>S7</DEVICE_ID>
            <DEVICE_NAME>C180 rotational home</DEVICE_NAME>
            <IP_ADDRESS>192.168.1.15</IP_ADDRESS>
            <CARD>
                <MANUFACTURER_ID>POWER-IO-01</MANUFACTURER_ID>
                <CARD_NAME>PowerIO</CARD_NAME>
                <CARD_ID>4</CARD_ID>
                <DEVICE_PORT_NO>21</DEVICE_PORT_NO>
            </CARD>
        </DEVICE_ADDRESS>
        <DEVICE_TYPE>SensorBoolDirect</DEVICE_TYPE>
        <INPUT_TYPE>PNP</INPUT_TYPE>
        <ACTIVE_HIGH>true</ACTIVE_HIGH>
        <ALARM>false</ALARM>
        <DEVICE_ID_AUX>???</DEVICE_ID_AUX>
    </SENSOR_BOOL_DIRECT>

  

<!-- Local sensors in each unit -->


 
    <SENSOR_LOCAL>
        <DEVICE_ADDRESS>
            <DEVICE_ID>L1-U1-S2</DEVICE_ID>
            <DEVICE_NAME>SEM 1 current consumption</DEVICE_NAME>
            <IP_ADDRESS>192.168.1.11</IP_ADDRESS>
            <CARD>
                <MANUFACTURER_ID>POWER-IO-01</MANUFACTURER_ID>
                <CARD_NAME>PowerIO</CARD_NAME>
                <CARD_ID>4</CARD_ID>
                <DEVICE_PORT_NO>31</DEVICE_PORT_NO>
            </CARD>
        </DEVICE_ADDRESS>
        <DEVICE_TYPE>SensorLocal</DEVICE_TYPE>
        <UNIT_CONVERSION>
            <INPUT_TYPE>0-10V</INPUT_TYPE>
            <!-- <OUTPUT_UNIT></OUTPUT_UNIT> -->
            <MIN_INPUT>405.3</MIN_INPUT>
            <MAX_INPUT>4096</MAX_INPUT>
            <MIN_OUTPUT>0</MIN_OUTPUT> 
            <MAX_OUTPUT>45.53</MAX_OUTPUT>
        </UNIT_CONVERSION>
        <THRESHOLDS>
            <ALARM_LOW></ALARM_LOW>
            <WARNING_LOW></WARNING_LOW>
            <WARNING_HIGH></WARNING_HIGH>
            <ALARM_HIGH></ALARM_HIGH>
        </THRESHOLDS>
        <DEVICE_ID_AUX>???</DEVICE_ID_AUX>
    </SENSOR_LOCAL>

  


    <SENSOR_LOCAL>
        <DEVICE_ADDRESS>
            <DEVICE_ID>L7-U1-S4</DEVICE_ID>
            <DEVICE_NAME>SEM 7 humidity</DEVICE_NAME>
            <IP_ADDRESS>192.168.1.17</IP_ADDRESS>
            <CARD>
                <MANUFACTURER_ID>POWER-IO-01</MANUFACTURER_ID>
                <CARD_NAME>PowerIO</CARD_NAME>
                <CARD_ID>4</CARD_ID>
                <DEVICE_PORT_NO>32</DEVICE_PORT_NO>
            </CARD>
        </DEVICE_ADDRESS>
        <DEVICE_TYPE>SensorLocal</DEVICE_TYPE>
        <UNIT_CONVERSION>
            <INPUT_TYPE>SPI</INPUT_TYPE>
            <!-- <OUTPUT_UNIT>%</OUTPUT_UNIT> -->
            <MIN_INPUT></MIN_INPUT>
            <MAX_INPUT></MAX_INPUT>
            <MIN_OUTPUT></MIN_OUTPUT> 
            <MAX_OUTPUT></MAX_OUTPUT>
        </UNIT_CONVERSION>
        <THRESHOLDS>
            <ALARM_LOW></ALARM_LOW>
            <WARNING_LOW></WARNING_LOW>
            <WARNING_HIGH></WARNING_HIGH>
            <ALARM_HIGH></ALARM_HIGH>
        </THRESHOLDS>
        <DEVICE_ID_AUX>???</DEVICE_ID_AUX>
    </SENSOR_LOCAL>

 

<!-- Solenoids -->


    <SOLENOID>
        <DEVICE_ADDRESS>
            <DEVICE_ID>V1</DEVICE_ID>
            <DEVICE_NAME>Habitat drain valve</DEVICE_NAME>
            <IP_ADDRESS>192.168.1.11</IP_ADDRESS>
            <CARD>
                <MANUFACTURER_ID>POWER-IO-01</MANUFACTURER_ID>
                <CARD_NAME>PowerIO</CARD_NAME>
                <CARD_ID>4</CARD_ID>
                <DEVICE_PORT_NO>37</DEVICE_PORT_NO>
            </CARD>
        </DEVICE_ADDRESS>
        <DEVICE_TYPE>Solenoid</DEVICE_TYPE>
        <MAX_CURRENT>2</MAX_CURRENT>
        <ACTIVATE_CURRENT>2</ACTIVATE_CURRENT>
        <HOLD_CURRENT>1</HOLD_CURRENT>
    </SOLENOID>

    <SOLENOID>
        <DEVICE_ADDRESS>
            <DEVICE_ID>V4</DEVICE_ID>
            <DEVICE_NAME>Air pressure valve</DEVICE_NAME>
            <IP_ADDRESS>192.168.1.13</IP_ADDRESS>
            <CARD>
                <MANUFACTURER_ID>POWER-IO-01</MANUFACTURER_ID>
                <CARD_NAME>PowerIO</CARD_NAME>
                <CARD_ID>4</CARD_ID>
                <DEVICE_PORT_NO>39</DEVICE_PORT_NO>
            </CARD>
        </DEVICE_ADDRESS>
        <DEVICE_TYPE>Solenoid</DEVICE_TYPE>
        <MAX_CURRENT>2</MAX_CURRENT>
        <ACTIVATE_CURRENT>2</ACTIVATE_CURRENT>
        <HOLD_CURRENT>1</HOLD_CURRENT>
    </SOLENOID>


<!-- PWM signals -->



    <PWM_SIGNAL>
        <DEVICE_ADDRESS>
            <DEVICE_ID>L2</DEVICE_ID>
            <DEVICE_NAME>LED lights inside habitat</DEVICE_NAME>
            <IP_ADDRESS>192.168.1.14</IP_ADDRESS>
            <CARD>
                <MANUFACTURER_ID>POWER-IO-01</MANUFACTURER_ID>
