=== perthi/logmaster/config/logging.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.1" vc:minVersion="1.1"
  xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning">
  <xs:simpleType name="LogLevel">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z,_]+[0-9]*"/>
      <!--  <xs:pattern value="[A-Z]+"/>-->
      <xs:enumeration value="DEBUG"/>
      <xs:enumeration value="INFO"/>
      <xs:enumeration value="WARNING"/>
      <xs:enumeration value="ERROR"/>
      <xs:enumeration value="FATAL"/>
      <xs:enumeration value="FATAL2"/>
      <xs:enumeration value="FORCE"/>
      <xs:enumeration value="FORCE_DEBUG"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="SystemType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="CmdLineTag">
    <xs:restriction base="xs:string">
      <xs:pattern value="--[a-z]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="LOGGING">
    <xs:complexType>
      <xs:sequence>


        <xs:element name="LEVELS">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="LOGLEVEL" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="LEVEL" type="LogLevel" maxOccurs="1" minOccurs="1"> </xs:element>                
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="SUBSYSTEMS">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="SYSTEM" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="NAME" type="SystemType" maxOccurs="1" minOccurs="1"> </xs:element>
                    <xs:element name="SHORT_NAME" type="SystemType" maxOccurs="1" minOccurs="1"> </xs:element>
                    <xs:element name="TAG" type="CmdLineTag" maxOccurs="1" minOccurs="1"/>
                    <xs:element name="TAG_SHORT" type="CmdLineTag" maxOccurs="1" minOccurs="1"/>
                    <xs:element name="DEFAULT" type="LogLevel" maxOccurs="1" minOccurs="1"/>
                    <xs:element name="CAN_MODIFY" type="xs:boolean" maxOccurs="1" minOccurs="1"/>
                    <xs:element name="FORCE_OUTPUT" type="xs:boolean" maxOccurs="1" minOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


</xs:schema>

=== perthi/logmaster/config/logging-kts.xml
<?xml version="1.0" encoding="UTF-8"?>




<LOGGING xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="logging.xsd">
    <LEVELS>
        <LOGLEVEL>
            <LEVEL>FATAL</LEVEL>
        </LOGLEVEL>
        <LOGLEVEL>
            <LEVEL>ERROR</LEVEL>
        </LOGLEVEL>
        <LOGLEVEL>
            <LEVEL>WARNING</LEVEL>
        </LOGLEVEL>
        <LOGLEVEL>
            <LEVEL>INFO</LEVEL>
        </LOGLEVEL>
        <LOGLEVEL>
            <LEVEL>DEBUG</LEVEL>
        </LOGLEVEL>
    </LEVELS>


    <SUBSYSTEMS>
        <SYSTEM>
            <NAME>FSM</NAME>
            <SHORT_NAME>FSM</SHORT_NAME>
            <TAG>--fsm</TAG>
            <TAG_SHORT>--fsm</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
        </SYSTEM>
        <SYSTEM>
            <NAME>MESSAGE</NAME>
            <SHORT_NAME>MSG</SHORT_NAME>
            <TAG>--message</TAG>
            <TAG_SHORT>--msg</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
        </SYSTEM>
        <SYSTEM>
            <NAME>COM</NAME>
            <SHORT_NAME>COM</SHORT_NAME>
            <TAG>--communication</TAG>
            <TAG_SHORT>--com</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
        </SYSTEM>        
        <SYSTEM> 
            <NAME>XML</NAME>
            <SHORT_NAME>XML</SHORT_NAME>
            <TAG>--xml</TAG>
            <TAG_SHORT>--xml</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>false</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
        </SYSTEM>
           <SYSTEM> 
            <NAME>DATABASE</NAME>
            <SHORT_NAME>DB</SHORT_NAME>
            <TAG>--database</TAG>
            <TAG_SHORT>--db</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
           </SYSTEM>
         <SYSTEM> 
            <NAME>JSON</NAME>
            <SHORT_NAME>JSON</SHORT_NAME>
            <TAG>--json</TAG>
            <TAG_SHORT>--j</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
         </SYSTEM>
           <SYSTEM> 
            <NAME>SHOTCAL</NAME>
            <SHORT_NAME>SC</SHORT_NAME>
            <TAG>--shotcal</TAG>
            <TAG_SHORT>--sc</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
         </SYSTEM>  
            <SYSTEM> 
            <NAME>SHOTEXCEC</NAME>
            <SHORT_NAME>SE</SHORT_NAME>
            <TAG>--shotexe</TAG>
            <TAG_SHORT>--se</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
         </SYSTEM>   
         <SYSTEM> 
            <NAME>CONFIGURATION</NAME>
            <SHORT_NAME>CONFIG</SHORT_NAME>
            <TAG>--configuration</TAG>
            <TAG_SHORT>--config</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
         </SYSTEM>   
         <SYSTEM> 
            <NAME>SENSOR</NAME>
            <SHORT_NAME>SENSOR</SHORT_NAME>
            <TAG>--sensor</TAG>
            <TAG_SHORT>--sensor</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
         </SYSTEM>
            <SYSTEM> 
            <NAME>CLI</NAME>
            <SHORT_NAME>CLI</SHORT_NAME>
            <TAG>--cli</TAG>
            <TAG_SHORT>--cli</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
            </SYSTEM>
            <SYSTEM> 
            <NAME>MCU</NAME>
            <SHORT_NAME>MCU</SHORT_NAME>
            <TAG>--mcu</TAG>
            <TAG_SHORT>--mcu</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
            </SYSTEM>
            

    </SUBSYSTEMS>

</LOGGING>

=== perthi/logmaster/config/logging-ucw.xml
<?xml version="1.0" encoding="UTF-8"?>

<LOGGING xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="logging.xsd">
    <LEVELS>
        <LOGLEVEL>
            <LEVEL>FATAL</LEVEL>
        </LOGLEVEL>
        <LOGLEVEL>
            <LEVEL>ERROR</LEVEL>
        </LOGLEVEL>
        <LOGLEVEL>
            <LEVEL>WARNING</LEVEL>
        </LOGLEVEL>
        <LOGLEVEL>
            <LEVEL>INFO</LEVEL>
        </LOGLEVEL>
        <LOGLEVEL>
            <LEVEL>DEBUG</LEVEL>
        </LOGLEVEL>
        <LOGLEVEL>
            <LEVEL>FORCE_DEBUG</LEVEL>
        </LOGLEVEL>
    </LEVELS>
    
    <SUBSYSTEMS>
        <SYSTEM>
            <NAME>EXCEPTION</NAME>
            <SHORT_NAME>EX</SHORT_NAME>
            <TAG>--exception</TAG>
            <TAG_SHORT>--ex</TAG_SHORT>
            <DEFAULT>ERROR</DEFAULT>
            <CAN_MODIFY>false</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
        </SYSTEM>
        <SYSTEM>
            <NAME>FSM</NAME>
            <SHORT_NAME>FSM</SHORT_NAME>
            <TAG>--fsm</TAG>
            <TAG_SHORT>--fsm</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
        </SYSTEM>
        <SYSTEM>
            <NAME>MEASUREMENT</NAME>
            <SHORT_NAME>MEAS</SHORT_NAME>
            <TAG>--measurement</TAG>
            <TAG_SHORT>--meas</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
        </SYSTEM>
        <SYSTEM>
            <NAME>CLI</NAME>
            <SHORT_NAME>CLI</SHORT_NAME>
            <TAG>--cli</TAG>
            <TAG_SHORT>--cli</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
        </SYSTEM>        
         <SYSTEM>
            <NAME>FOC</NAME>
            <SHORT_NAME>FOC</SHORT_NAME>
            <TAG>--foc</TAG>
            <TAG_SHORT>--foc</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
        </SYSTEM>
         <SYSTEM>
            <NAME>COM</NAME>
            <SHORT_NAME>COM</SHORT_NAME>
            <TAG>--com</TAG>
            <TAG_SHORT>--com</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
        </SYSTEM>      
        <SYSTEM> 
            <NAME>XML</NAME>
            <SHORT_NAME>XML</SHORT_NAME>
            <TAG>--xml</TAG>
            <TAG_SHORT>--xml</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
        </SYSTEM>
           <SYSTEM> 
            <NAME>DATABASE</NAME>
            <SHORT_NAME>DB</SHORT_NAME>
            <TAG>--database</TAG>
            <TAG_SHORT>--db</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
          </SYSTEM>
        <SYSTEM> 
            <NAME>USER</NAME>
            <SHORT_NAME>USR</SHORT_NAME>
            <TAG>--user</TAG>
            <TAG_SHORT>--usr</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
        </SYSTEM>
        <SYSTEM> 
            <NAME>GENERAL</NAME>
            <SHORT_NAME>G</SHORT_NAME>
            <TAG>--general</TAG>
            <TAG_SHORT>--gen</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
        </SYSTEM>
        <SYSTEM> 
            <NAME>ALARM</NAME>
            <SHORT_NAME>ALARM</SHORT_NAME>
            <TAG>--alarm</TAG>
            <TAG_SHORT>--alarm</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>false</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
        </SYSTEM>
    </SUBSYSTEMS>

</LOGGING>

=== perthi/logmaster/config/logging.xml
<?xml version="1.0" encoding="UTF-8"?>




<LOGGING xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="logging.xsd">
    <LEVELS>
        <LOGLEVEL>
            <LEVEL>DEBUG</LEVEL>
        </LOGLEVEL>
        <LOGLEVEL>
            <LEVEL>INFO</LEVEL>
        </LOGLEVEL>
        <LOGLEVEL>
            <LEVEL>WARNING</LEVEL>
        </LOGLEVEL>
        <LOGLEVEL>
            <LEVEL>ERROR</LEVEL>
        </LOGLEVEL>
        <LOGLEVEL>
            <LEVEL>FATAL</LEVEL>
        </LOGLEVEL>
    </LEVELS>


    <SUBSYSTEMS>
        <SYSTEM>
            <NAME>FSM</NAME>
            <SHORT_NAME>FSM</SHORT_NAME>
            <TAG>--fsm</TAG>
            <TAG_SHORT>--fsm</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
        </SYSTEM>
        <SYSTEM>
            <NAME>MESSAGE</NAME>
            <SHORT_NAME>MSG</SHORT_NAME>
            <TAG>--message</TAG>
            <TAG_SHORT>--msg</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
        </SYSTEM>
        <SYSTEM>
            <NAME>COM</NAME>
            <SHORT_NAME>COM</SHORT_NAME>
            <TAG>--com</TAG>
            <TAG_SHORT>--com</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>true</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
        </SYSTEM>        
        <SYSTEM> 
            <NAME>XML</NAME>
            <SHORT_NAME>XML</SHORT_NAME>
            <TAG>--xml</TAG>
            <TAG_SHORT>--xml</TAG_SHORT>
            <DEFAULT>WARNING</DEFAULT>
            <CAN_MODIFY>false</CAN_MODIFY>
            <FORCE_OUTPUT>false</FORCE_OUTPUT>
        </SYSTEM>


    </SUBSYSTEMS>

</LOGGING>
